name: suupr_tests
description: "No-code E2E orchestration framework for automated Flutter testing using VM Service extensions."
version: 1.0.0-beta.2
homepage: https://duupr.io
repository: https://github.com/duupr/suuprtests
issue_tracker: https://github.com/duupr/suuprtests/issues

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vm_service: ^15.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

topics:
  - testing
  - automation
  - e2e
  - widget-testing

flutter:
